### PR TITLE
rebranding elements

### PR DESCRIPTION
**Pull request by menschikov**

### CODE REVIEW

**Comment by AugustoL** [comment]
@menschikov can you remove .DS_STORE files?

**Comment by AugustoL** [comment]
Also, the old folder makes o sense to keep it, maybe keep only `old/README.md`

**Comment by AugustoL** [comment]
And there is some old logos in the root too. We should remove them too.

**Comment by menschikov** [comment]
I've deleted DS_store please check, also put the readme file to rood directory. Didn't delete the "old" folder, don't know if someboby still uses it - if somebody still use old resources via url, they need to change url to /old/ subfolder, until they desing their websites/apps/articles with new elements

**Pull request merged**
